In [23]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# a班

In [24]:
a=np.random.randint(0,100,50)
a=np.array(a)
a.shape=(10,5)
a

array([[84, 79, 90,  3,  3],
       [73, 14, 39, 78, 22],
       [68, 88, 33,  3, 12],
       [93, 98, 46, 33, 63],
       [23, 48, 12, 67, 80],
       [86, 18, 75, 39,  8],
       [70, 79, 22, 87, 92],
       [69, 73, 45, 66, 87],
       [ 1, 37, 37,  2, 80],
       [42, 11, 37, 21, 70]])

In [25]:
w=[0.25,0.25,0.25,0.15,0.10]
np.dot(a,w)

array([64.  , 45.4 , 48.9 , 70.5 , 38.8 , 51.4 , 65.  , 65.35, 27.05,
       32.65])

# b班

In [27]:
b=np.random.randint(0,100,50)
b=np.array(b)
b.shape=(10,5)
b

array([[16, 98, 94,  6, 45],
       [68, 96, 14, 80, 67],
       [52, 46,  6, 24,  5],
       [18, 17, 18, 48, 68],
       [67, 98, 62, 44, 63],
       [76, 63, 59, 31, 42],
       [85, 66, 43, 86, 74],
       [34, 20, 76, 42, 88],
       [62, 51, 91,  3, 37],
       [93, 23, 31, 49, 38]])

In [28]:
w=[0.25,0.25,0.25,0.15,0.10]
np.dot(b,w)

array([57.4 , 63.2 , 30.1 , 27.25, 69.65, 58.35, 68.8 , 47.6 , 55.15,
       47.9 ])

# c班

In [29]:
c=np.random.randint(0,100,50)
c=np.array(c)
c.shape=(10,5)
c

array([[37,  2, 15, 98, 72],
       [10, 89, 92, 23, 19],
       [46, 75, 19, 15, 66],
       [ 0, 13, 85, 93, 39],
       [ 8,  9, 41, 61, 61],
       [16, 50, 55, 34, 98],
       [37, 40, 58, 80, 68],
       [ 6, 64, 96, 90, 32],
       [71, 23, 54, 63,  1],
       [76, 40, 75, 32, 11]])

In [30]:
w=[0.25,0.25,0.25,0.15,0.10]
np.dot(c,w)

array([35.4 , 53.1 , 43.85, 42.35, 29.75, 45.15, 52.55, 58.2 , 46.55,
       53.65])